---
device: multi
input_channel: 6
obsv_len: 5
pred_len: 20
---
batch_size: 20
checkpoint_dir: Model/ALD
early_stopping: 0
epoch: 10
learning_rate: 0.001
weight_regularization: 0.0001
---
data_name: ALD_1t20_train
data_path: data/ALD_1t20_train
label_path: data/ALD_1t20_train/all_data.csv
model_path: Model/ald_1t20_trial_pos
