---
device: multi
input_channel: 6
obsv_len: 5
pred_len: 20
---
batch_size: 20
checkpoint_dir: Model/GCD
early_stopping: 0
epoch: 20
learning_rate: 0.001
weight_regularization: 0.0001
---
data_name: GCD_1t20_train
data_path: Data/GCD_1t20_train
label_path: Data/GCD_1t20_train/all_data.csv
model_path: Model/gcd_1t20_b_bce_sigma20
