---
device: multi
dynamic_env: false
input_channel: 10
obsv_len: 9
pred_len: 12
---
batch_size: 20
checkpoint_dir: Model/
early_stopping: 0
epoch: 20
learning_rate: 0.001
weight_regularization: 0.0001
---
cell_width: 1
x_max_px: 595
y_max_px: 326
---
data_name: SDD_1t12seg_test
data_path: data/SDD_1t12seg_test
label_path: data/SDD_1t12seg_test/all_data.csv
model_path: Model/sdd_1t12_pelu_2
