---
device: multi
dynamic_env: true
input_channel: 10
obsv_len: 5
pred_len: 1
---
batch_size: 20
checkpoint_dir: Model/
early_stopping: 0
epoch: 20
learning_rate: 0.001
weight_regularization: 0.0001
---
cell_width: 1
x_max_px: 595
y_max_px: 326
---
data_name: SID_20_test
data_path: Data/SID_20_test
label_csv: all_data.csv
label_path: Data/SID_20_test/all_data.csv
model_path: Model/sid_20
