---
device: multi
dynamic_env: true
input_channel: 10
obsv_len: 5
pred_len: 10
---
batch_size: 20
checkpoint_dir: Model/
early_stopping: 0
epoch: 20
learning_rate: 0.001
weight_regularization: 0.0001
---
cell_width: 1
x_max_px: 595
y_max_px: 326
---
data_name: SID_1t10_train
data_path: data/SID_1t10_train
label_path: data/SID_1t10_train/all_data.csv
model_path: Model/sid_1t10
