---
device: multi
input_channel: 6
obsv_len: 5
pred_len: 10
---
batch_size: 20
checkpoint_dir: Model/SID2c
early_stopping: 0
epoch: 20
learning_rate: 0.001
weight_regularization: 0.0001
---
data_name: SID_1t10_train/3
data_path: Data/SID_1t10_train/3
label_path: Data/SID_1t10_train/3/all_data.csv
model_path: Model/sidv2c_1t10
