---
device: multi
input_channel: 6
obsv_len: 5
pred_len: 10
---
batch_size: 20
checkpoint_dir: Model/SID2a
early_stopping: 0
epoch: 20
learning_rate: 0.001
weight_regularization: 0.0001
---
data_name: SIDv2_1t10_train/1
data_path: Data/SIDv2_1t10_train/1
label_path: Data/SIDv2_1t10_train/1/all_data.csv
model_path: Model/sidv2a_1t10_sigma5_bce
