#!/usr/bin/env bash
#SBATCH -A SNIC2021-7-117 -p alvis
#SBATCH -N 1
#SBATCH --gpus-per-node=A40:3
#SBATCH -t 6-23:00:00

ml load GCC/10.2.0
ml load CUDA/11.1.1-GCC-10.2.0
ml load OpenMPI/4.0.5-gcccuda-2020b
ml load PyTorch/1.8.1-fosscuda-2020b
ml load torchvision/0.9.1-fosscuda-2020b-PyTorch-1.8.1

ml load matplotlib/3.3.3-fosscuda-2020b
ml load Pillow/8.0.1-GCCcore-10.2.0
# ml load scikit-image/0.18.1-fosscuda-2020b

# export PYTHONPATH=$PYTHONPATH:~/lib/python3.7/site-packages/

python -u src/main_train.py "$@"
# python -u src/runtime_check.py "$@"
